### ISSUE TITLE
Add if name condition to script

### ISSUE THREAD

**Issue by ronentk** [csensemakers/desci-sense#73]
@ShaRefOh 
There should be an 
```
if __name__ == "__main__":
``` 
condition before the script
https://github.com/csensemakers/desci-sense/blob/256b6c4c912e5503a8a0ff566ebc3d253051567b/desci_sense/evaluation/eval_benchmark_v0.py#L98

(see [here](https://stackoverflow.com/questions/419163/what-does-if-name-main-do) for explanation)

And see here for an example
https://github.com/csensemakers/desci-sense/blob/256b6c4c912e5503a8a0ff566ebc3d253051567b/scripts/get_wandb_data.py#L84C1-L85C1

**Comment by ShaRefOh** [comment]
Sure, do you think we will use this script as a module? It does make sense if we want to run some specific checkups

**Comment by ronentk** [comment]
Not necessarily, but it's just considered good practice when writing python scripts :)
