### ISSUE TITLE
Add modified multilabel confusion matrix

### ISSUE THREAD

**Issue by ronentk** [csensemakers/desci-sense#80]

**Comment by ShaRefOh** [comment]
See https://wandb.ai/common-sense-makers/evaluation_benchmark/runs/gzxxek1w?
## How to read the matrix:
**On the diagonal** you see the true positives.
**Off diagonal** You see the false positives as long as the row label predicted is a false negative.

This lets you see, when a label is not chosen correctly, which are the other falsely predicted labels that (might) have been predicted instead.

# Note

We do not use regular confusion matrix as this is a multi-label problem.
